### ISSUE TITLE
Inaccurate rate function

### ISSUE THREAD

**Issue by cf-ron** [Conor-CC/django-rest-loan-calculator#1]
Hi,
I haven't looked to deep in the code but I wanted to highlight something that might change your solution, specifically the rate threshold option.
In Numpy, the rate function assumes monthly interest calculation but in our case the interest is calculated on daily basis.
The attached document shows an accurate calculation of a loan. If you use the rate function for the same parameters, you will get a rate of 12%, while the accurate answer is a bit less than that.
[Loan calculation example.xlsx](https://github.com/Conor-CC/django-rest-loan-calculator/files/5062291/Loan.calculation.example.xlsx)

**Comment by Conor-CC** [comment]
Hi Ron,
Thanks for the comment! I ended up manually configuring all of the calculations instead of using Numpy. 

Indeed the two endpoints for the Monthly Repayment Calculation ('/loan-calc/monthly-repayment/') and the Number of Repayments Calculation ('/loan-calc/repayment-count/') both assume a monthly rate which I think lines up with the spec but please correct me if I'm wrong. The Interest threshold does assume a monthly rate as well. 

I passed the same parameters as you used in your example to the '/loan-calc/interest-rate/' end point and got an interest rate of 11.98260033% vs your more accurate 11.983126784%.

Results yielded from passing specified parameters:
![image](https://user-images.githubusercontent.com/34569973/90011402-73da1300-dc99-11ea-88a6-968e71721818.png)

I'll see what I can do to address this today. Modifying parameters in `def m(r)` and `def m_inverse(r)` in cflow/loanCalc/calculators.py should be a good start though I think!

**Comment by cf-ron** [comment]
That's fine @Conor-CC 
You don't need to go into that rabbit hole, your result is fine :)

**Comment by Conor-CC** [comment]
No worries, just thought it was interesting nonetheless! Some tweaking of the polynomials and the parameters they receive would be needed for sure to produce more accurate results for daily interest. 

Are there any resources you could recommend where I could learn a bit more about how to go about calculating interest on a daily basis?
